### ISSUE TITLE
PIVX Sapling params are not copied to .pivx-params folder

### ISSUE THREAD

**Issue by PalmTreeVI** [richardltc/boxwallet#2]
I tried the linux 64 version on a pc and the arm64 on a raspberry pi, both installs failed to copy the files to the ~/.pivx-params folder.  The pivx error log displays:  

```2022-02-05T20:46:02Z Error: Cannot find the Sapling parameters in the following directory:
"/home/guest/.pivx-params"```

**Comment by richardltc** [comment]
All fixed in latest release
